# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - AzureContainers/src/**
pool:
  vmImage: ubuntu-latest
variables:
  VmImageName: 'ubuntu-latest'
  Solution: 'src/dockerDemo.csproj'
  DOTNETVERSION: '10.x'
stages:
- stage: Build
  displayName: 'Build & Package Container Code'
  jobs:
    - job: Build
      displayName: Build
      pool:
       vmImage: 'ubuntu-latest'
      steps:
        - task: UseDotNet@2
          displayName: 'Install .NET 10'
          inputs:
            version: '$(DOTNETVERSION)'
            includePreviewVersions: true
        - task: DotNetCoreCLI@2
          displayName: 'Build Solution'
          inputs:
           command: 'build'
           projects: '$(Solution)'
        # Copy Bicep Files
        - task: CopyFiles@2
          displayName: 'Copy Bicep files'
          inputs:
            sourceFolder: '$(System.DefaultWorkingDirectory)'
            contents: '**/Deployment/Bicep/**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: CopyFiles@2
          displayName: 'Copy Source Files'
          inputs:
           sourceFolder: '$(System.DefaultWorkingDirectory)'
           contents: '**/src/**'
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          displayName: 'Pubishing Artifacts'
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: Container
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
